-- Create the table
create table public.ride_recaps (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  total_distance numeric,
  locations text[],
  favorite_time text,
  favorite_terrain text,
  longest_ride numeric,
  favorite_day text,
  preferred_weather text,
  ride_length text,
  memorable_moment text,
  motorcycle_name text,
  personality text
);

-- Enable Row Level Security (RLS)
alter table public.ride_recaps enable row level security;

-- Create a policy to allow anyone to insert data (since it's a public form)
create policy "Enable insert for everyone" 
on "public"."ride_recaps" 
as PERMISSIVE 
for INSERT 
to public 
with check (true);

-- Optional: Create a policy to allow reading (if you want to show leaderboards later)
-- create policy "Enable read for everyone" 
-- on "public"."ride_recaps" 
-- as PERMISSIVE 
-- for SELECT 
-- to public 
-- using (true);
